/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
ALTER TABLE "anamnesi"
	DROP FOREIGN KEY "paziente_anamnesi"
GO
ALTER TABLE "anamnesi"
	DROP FOREIGN KEY "anamnesi_tipo_malattia"
GO
DROP INDEX "patologia_concomitante_tipo_malattia_idx" ON anamnesi
GO
DROP INDEX "paziente_patologia_concomitante_idx" ON anamnesi
GO
DROP TABLE "anamnesi"
GO
CREATE TABLE "anamnesi"  ( 
	"idpatologia_concomitante"	int(11) AUTO_INCREMENT NOT NULL,
	"id_paziente"             	int(11) NOT NULL,
	"id_tipo_malattia"        	int(11) NOT NULL,
	"descrizione"             	varchar(255) NULL,
	PRIMARY KEY("idpatologia_concomitante")
)
GO
CREATE INDEX "patologia_concomitante_tipo_malattia_idx" USING BTREE 
	ON "anamnesi"("id_tipo_malattia")
GO
CREATE INDEX "paziente_patologia_concomitante_idx" USING BTREE 
	ON "anamnesi"("id_paziente")
GO
ALTER TABLE "anamnesi"
	ADD CONSTRAINT "paziente_anamnesi"
	FOREIGN KEY("id_paziente")
	REFERENCES "paziente"("idPAZIENTE")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "anamnesi"
	ADD CONSTRAINT "anamnesi_tipo_malattia"
	FOREIGN KEY("id_tipo_malattia")
	REFERENCES "tipo_malattia"("idtipo_malattia")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
