/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
DROP TABLE "cod_tipo_sospensione"
GO
CREATE TABLE "cod_tipo_sospensione"  ( 
	"cod_tipo_sospensione"	char(1) NOT NULL,
	"descrizione"         	varchar(45) NOT NULL,
	PRIMARY KEY("cod_tipo_sospensione")
)
GO
