/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
ALTER TABLE "diagnosi_malattia"
	DROP FOREIGN KEY "paziente"
GO
ALTER TABLE "diagnosi_malattia"
	DROP FOREIGN KEY "malattia"
GO
ALTER TABLE "diagnosi_malattia"
	DROP FOREIGN KEY "flag_fattore_reumatoide"
GO
ALTER TABLE "diagnosi_malattia"
	DROP FOREIGN KEY "flag_anticorpi"
GO
DROP INDEX "flag_anticorpi_idx" ON diagnosi_malattia
GO
DROP INDEX "flag_fattore_reumatoide_idx" ON diagnosi_malattia
GO
DROP INDEX "malattia_idx" ON diagnosi_malattia
GO
DROP INDEX "paziente_idx" ON diagnosi_malattia
GO
DROP TABLE "diagnosi_malattia"
GO
CREATE TABLE "diagnosi_malattia"  ( 
	"iddiagnosi_malattia"	int(11) AUTO_INCREMENT NOT NULL,
	"cod_malattia"       	int(11) NULL,
	"data_diagnosi"      	date NOT NULL,
	"anticorpi"          	char(1) NULL,
	"fattore_reumatoide" 	char(1) NULL,
	"id_paziente"        	int(11) NOT NULL,
	PRIMARY KEY("iddiagnosi_malattia")
)
GO
CREATE INDEX "flag_anticorpi_idx" USING BTREE 
	ON "diagnosi_malattia"("anticorpi")
GO
CREATE INDEX "flag_fattore_reumatoide_idx" USING BTREE 
	ON "diagnosi_malattia"("fattore_reumatoide")
GO
CREATE INDEX "malattia_idx" USING BTREE 
	ON "diagnosi_malattia"("cod_malattia")
GO
CREATE INDEX "paziente_idx" USING BTREE 
	ON "diagnosi_malattia"("id_paziente")
GO
ALTER TABLE "diagnosi_malattia"
	ADD CONSTRAINT "paziente"
	FOREIGN KEY("id_paziente")
	REFERENCES "paziente"("idPAZIENTE")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "diagnosi_malattia"
	ADD CONSTRAINT "malattia"
	FOREIGN KEY("cod_malattia")
	REFERENCES "tipo_malattia"("idtipo_malattia")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "diagnosi_malattia"
	ADD CONSTRAINT "flag_fattore_reumatoide"
	FOREIGN KEY("fattore_reumatoide")
	REFERENCES "tipo_risposta"("idtipo_risposta")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
ALTER TABLE "diagnosi_malattia"
	ADD CONSTRAINT "flag_anticorpi"
	FOREIGN KEY("anticorpi")
	REFERENCES "tipo_risposta"("idtipo_risposta")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
