/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
ALTER TABLE "infusioni_tcz"
	DROP INDEX "idinfusioni_TCZ_UNIQUE"
GO
ALTER TABLE "infusioni_tcz"
	DROP INDEX "data_inf"
GO
DROP TABLE "infusioni_tcz"
GO
CREATE TABLE "infusioni_tcz"  ( 
	"idinfusioni_TCZ"	int(11) AUTO_INCREMENT NOT NULL,
	"id_paziente"    	int(11) NULL,
	"data_infusione" 	date NOT NULL,
	PRIMARY KEY("idinfusioni_TCZ")
)
GO
ALTER TABLE "infusioni_tcz"
	ADD CONSTRAINT "idinfusioni_TCZ_UNIQUE"
	UNIQUE ("idinfusioni_TCZ")
GO
ALTER TABLE "infusioni_tcz"
	ADD CONSTRAINT "data_inf"
	UNIQUE ("id_paziente", "data_infusione")
GO
