/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
ALTER TABLE "paziente"
	DROP FOREIGN KEY "utente_applicativo"
GO
ALTER TABLE "paziente"
	DROP INDEX "idPAZIENTE_UNIQUE"
GO
DROP INDEX "application_user_idx" ON paziente
GO
DROP TABLE "paziente"
GO
CREATE TABLE "paziente"  ( 
	"idPAZIENTE"           	int(11) AUTO_INCREMENT NOT NULL,
	"NOME"                 	varchar(25) NOT NULL,
	"COGNOME"              	varchar(25) NOT NULL,
	"DATA_NASCITA"         	date NOT NULL,
	"CODICE_FISCALE"       	varchar(16) NULL,
	"sesso"                	char(1) NULL,
	"DATA_INSERIMENTO"     	timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"ID_UTENTE_INSERIMENTO"	int(11) NULL,
	"attivo"               	bit(1) NOT NULL DEFAULT 'b'1'',
	"data_fine"            	date NULL,
	PRIMARY KEY("idPAZIENTE")
)
GO
CREATE INDEX "application_user_idx" USING BTREE 
	ON "paziente"("ID_UTENTE_INSERIMENTO")
GO
ALTER TABLE "paziente"
	ADD CONSTRAINT "idPAZIENTE_UNIQUE"
	UNIQUE ("idPAZIENTE")
GO
ALTER TABLE "paziente"
	ADD CONSTRAINT "utente_applicativo"
	FOREIGN KEY("ID_UTENTE_INSERIMENTO")
	REFERENCES "utenti"("idutenti")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
