/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: VIEW
*/
DROP VIEW "rptfattoririschio"
GO
CREATE VIEW "rptfattoririschio"
AS
select `artrite`.`paziente`.`idPAZIENTE` AS `idPAZIENTE`,`artrite`.`paziente`.`sesso` AS `sesso`,`artrite`.`tipo_malattia`.`descrizione` AS `malattia`,`artrite`.`tipo_cod_malattia`.`tipo_malattia` AS `tipo_malattia`,`artrite`.`tipo_cod_malattia`.`idtipo_cod_malattia` AS `idtipo_cod_malattia` from (((`artrite`.`anamnesi` join `artrite`.`tipo_malattia` on((`artrite`.`anamnesi`.`id_tipo_malattia` = `artrite`.`tipo_malattia`.`idtipo_malattia`))) join `artrite`.`paziente` on((`artrite`.`paziente`.`idPAZIENTE` = `artrite`.`anamnesi`.`id_paziente`))) join `artrite`.`tipo_cod_malattia` on((`artrite`.`tipo_malattia`.`cod_tipo_malattia` = `artrite`.`tipo_cod_malattia`.`idtipo_cod_malattia`))) where (`artrite`.`tipo_cod_malattia`.`idtipo_cod_malattia` = 'FDR')
GO
