/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: VIEW
*/
DROP VIEW "rptterapia_concomitante"
GO
CREATE VIEW "rptterapia_concomitante"
AS
select `artrite`.`paziente`.`idPAZIENTE` AS `idPAZIENTE`,`artrite`.`paziente`.`sesso` AS `sesso`,`artrite`.`tipo_farmaco`.`nome` AS `nome`,`artrite`.`terapia_concomitante`.`dose` AS `dose` from ((`artrite`.`terapia_concomitante` join `artrite`.`tipo_farmaco` on((`artrite`.`terapia_concomitante`.`id_tipo_farmaco` = `artrite`.`tipo_farmaco`.`idtipo_farmaco`))) join `artrite`.`paziente` on((`artrite`.`paziente`.`idPAZIENTE` = `artrite`.`terapia_concomitante`.`id_paziente`))) order by `artrite`.`paziente`.`idPAZIENTE`
GO
