/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: VIEW
*/
DROP VIEW "rptvalutazione_terapia"
GO
CREATE VIEW "rptvalutazione_terapia"
AS
select `artrite`.`paziente`.`idPAZIENTE` AS `idPAZIENTE`,`artrite`.`paziente`.`sesso` AS `sesso`,`artrite`.`terapia_valutazione`.`art_dolenti` AS `art_dolenti`,`artrite`.`terapia_valutazione`.`art_tumefatte` AS `art_tumefatte`,`artrite`.`terapia_valutazione`.`pcr` AS `pcr`,`artrite`.`terapia_valutazione`.`ves` AS `ves`,`artrite`.`terapia_valutazione`.`vas_paziente` AS `vas_paziente`,`artrite`.`terapia_valutazione`.`vas_medico` AS `vas_medico`,`artrite`.`terapia_valutazione`.`das28` AS `das28`,`artrite`.`terapia_valutazione`.`sdai` AS `sdai`,`artrite`.`terapia_valutazione`.`cdai` AS `cdai`,`artrite`.`terapia_valutazione`.`tempo` AS `tempo` from (`artrite`.`paziente` join `artrite`.`terapia_valutazione` on((`artrite`.`paziente`.`idPAZIENTE` = `artrite`.`terapia_valutazione`.`id_paziente`))) order by `artrite`.`paziente`.`idPAZIENTE`,`artrite`.`terapia_valutazione`.`tempo`
GO
