/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
ALTER TABLE "terapia_farmacologica_pre"
	DROP FOREIGN KEY "paziente_terapia_farmacologica_pre"
GO
DROP INDEX "paziente_idx" ON terapia_farmacologica_pre
GO
DROP TABLE "terapia_farmacologica_pre"
GO
CREATE TABLE "terapia_farmacologica_pre"  ( 
	"idterapia_farmacologica_pre"	int(11) AUTO_INCREMENT NOT NULL,
	"id_paziente"                	int(11) NOT NULL,
	"cod_tipo_farmaco"           	int(11) NOT NULL,
	PRIMARY KEY("idterapia_farmacologica_pre")
)
GO
CREATE INDEX "paziente_idx" USING BTREE 
	ON "terapia_farmacologica_pre"("id_paziente")
GO
ALTER TABLE "terapia_farmacologica_pre"
	ADD CONSTRAINT "paziente_terapia_farmacologica_pre"
	FOREIGN KEY("id_paziente")
	REFERENCES "paziente"("idPAZIENTE")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
