/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
DROP TABLE "terapia_concomitante"
GO
CREATE TABLE "terapia_concomitante"  ( 
	"idterapia_concomitante"   	int(11) AUTO_INCREMENT NOT NULL,
	"id_terapia"               	int(11) NOT NULL,
	"id_tipo_farmaco"          	int(11) NOT NULL,
	"dose"                     	decimal(10,4) NULL,
	"id_paziente"              	int(11) NOT NULL,
	"tempo"                    	int(11) NULL,
	"d_inizio"                 	date NULL,
	"d_fine"                   	date NULL,
	"note"                     	varchar(250) NULL,
	"idtipo_motivo_sospensione"	int(11) NULL,
	PRIMARY KEY("idterapia_concomitante")
)
GO
