/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
DROP TABLE "terapia"
GO
CREATE TABLE "terapia"  ( 
	"idterapia"  	int(11) AUTO_INCREMENT NOT NULL,
	"id_paziente"	int(11) NOT NULL,
	"data_inizio"	date NOT NULL,
	PRIMARY KEY("idterapia","id_paziente")
)
GO
