/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
ALTER TABLE "terapia_valutazione"
	DROP INDEX "idterapia_valutazione_UNIQUE"
GO
DROP TABLE "terapia_valutazione"
GO
CREATE TABLE "terapia_valutazione"  ( 
	"idterapia_valutazione"	int(11) AUTO_INCREMENT NOT NULL,
	"id_terapia"           	int(11) NULL,
	"id_paziente"          	int(11) NOT NULL,
	"art_dolenti"          	int(11) NULL,
	"art_tumefatte"        	int(11) NULL,
	"pcr"                  	decimal(10,2) NULL,
	"ves"                  	decimal(10,2) NULL,
	"vas_paziente"         	decimal(10,2) NULL,
	"vas_medico"           	decimal(10,2) NULL,
	"das28"                	decimal(10,2) NULL,
	"sdai"                 	decimal(10,2) NULL,
	"cdai"                 	decimal(10,2) NULL,
	"data_valutazione"     	datetime NULL,
	"tempo"                	int(11) NOT NULL,
	PRIMARY KEY("idterapia_valutazione")
)
GO
ALTER TABLE "terapia_valutazione"
	ADD CONSTRAINT "idterapia_valutazione_UNIQUE"
	UNIQUE ("idterapia_valutazione")
GO
