/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
DROP TABLE "test"
GO
CREATE TABLE "test"  ( 
	"nr"	int(11) NOT NULL 
	)
GO
