/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
ALTER TABLE "tipo_malattia"
	DROP FOREIGN KEY "cod_tipo_malattia"
GO
DROP INDEX "cod_tipo_malattia_idx" ON tipo_malattia
GO
DROP TABLE "tipo_malattia"
GO
CREATE TABLE "tipo_malattia"  ( 
	"idtipo_malattia"  	int(11) AUTO_INCREMENT NOT NULL,
	"descrizione"      	varchar(45) NOT NULL,
	"cod_tipo_malattia"	char(3) NOT NULL,
	PRIMARY KEY("idtipo_malattia")
)
COMMENT = 'anagrafica delle malattie' 
GO
CREATE INDEX "cod_tipo_malattia_idx" USING BTREE 
	ON "tipo_malattia"("cod_tipo_malattia")
GO
ALTER TABLE "tipo_malattia"
	ADD CONSTRAINT "cod_tipo_malattia"
	FOREIGN KEY("cod_tipo_malattia")
	REFERENCES "tipo_cod_malattia"("idtipo_cod_malattia")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
