/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
ALTER TABLE "tipo_sospensione_dettaglio"
	DROP FOREIGN KEY "tipo_sospensione_tipo_sospensione_dettaglio"
GO
DROP INDEX "tipo_sospensione_tipo_sospensione_dettaglio_idx" ON tipo_sospensione_dettaglio
GO
DROP TABLE "tipo_sospensione_dettaglio"
GO
CREATE TABLE "tipo_sospensione_dettaglio"  ( 
	"id_sospensione_dettaglio"	int(11) AUTO_INCREMENT NOT NULL,
	"id_tipo_sospensione"     	int(11) NOT NULL,
	"sospensione_dettaglio"   	varchar(45) NOT NULL,
	PRIMARY KEY("id_sospensione_dettaglio")
)
GO
CREATE INDEX "tipo_sospensione_tipo_sospensione_dettaglio_idx" USING BTREE 
	ON "tipo_sospensione_dettaglio"("id_tipo_sospensione")
GO
ALTER TABLE "tipo_sospensione_dettaglio"
	ADD CONSTRAINT "tipo_sospensione_tipo_sospensione_dettaglio"
	FOREIGN KEY("id_tipo_sospensione")
	REFERENCES "tipo_sospensione"("idtipo_motivo_sospensione")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
