/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
ALTER TABLE "tipo_farmaco"
	DROP FOREIGN KEY "famiglia_farmaco"
GO
ALTER TABLE "tipo_farmaco"
	DROP INDEX "nome_UNIQUE"
GO
DROP INDEX "famiglia_farmaco_idx" ON tipo_farmaco
GO
DROP TABLE "tipo_farmaco"
GO
CREATE TABLE "tipo_farmaco"  ( 
	"idtipo_farmaco"       	int(11) AUTO_INCREMENT NOT NULL,
	"tipo_famiglia_farmaco"	int(11) NOT NULL,
	"nome"                 	varchar(25) NOT NULL,
	PRIMARY KEY("idtipo_farmaco")
)
GO
CREATE INDEX "famiglia_farmaco_idx" USING BTREE 
	ON "tipo_farmaco"("tipo_famiglia_farmaco")
GO
ALTER TABLE "tipo_farmaco"
	ADD CONSTRAINT "nome_UNIQUE"
	UNIQUE ("nome")
GO
ALTER TABLE "tipo_farmaco"
	ADD CONSTRAINT "famiglia_farmaco"
	FOREIGN KEY("tipo_famiglia_farmaco")
	REFERENCES "tipo_famiglia_farmaco"("idtipo_famiglia_farmaco")
	ON DELETE NO ACTION 
	ON UPDATE NO ACTION 
GO
