/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
ALTER TABLE "tipo_risposta"
	DROP INDEX "risposta_UNIQUE"
GO
DROP TABLE "tipo_risposta"
GO
CREATE TABLE "tipo_risposta"  ( 
	"idtipo_risposta"	char(1) NOT NULL,
	"risposta"       	varchar(16) NOT NULL,
	PRIMARY KEY("idtipo_risposta")
)
GO
ALTER TABLE "tipo_risposta"
	ADD CONSTRAINT "risposta_UNIQUE"
	UNIQUE ("risposta")
GO
