/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
ALTER TABLE "tipo_cod_malattia"
	DROP INDEX "tipo_malattia_UNIQUE"
GO
DROP TABLE "tipo_cod_malattia"
GO
CREATE TABLE "tipo_cod_malattia"  ( 
	"idtipo_cod_malattia"	char(3) NOT NULL,
	"tipo_malattia"      	varchar(45) NOT NULL,
	PRIMARY KEY("idtipo_cod_malattia")
)
GO
ALTER TABLE "tipo_cod_malattia"
	ADD CONSTRAINT "tipo_malattia_UNIQUE"
	UNIQUE ("tipo_malattia")
GO
