/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
ALTER TABLE "tipo_famiglia_farmaco"
	DROP INDEX "famiglia_farmacocol_UNIQUE"
GO
DROP TABLE "tipo_famiglia_farmaco"
GO
CREATE TABLE "tipo_famiglia_farmaco"  ( 
	"idtipo_famiglia_farmaco"	int(11) NOT NULL,
	"famiglia_farmacocol"    	varchar(45) NOT NULL,
	PRIMARY KEY("idtipo_famiglia_farmaco")
)
GO
ALTER TABLE "tipo_famiglia_farmaco"
	ADD CONSTRAINT "famiglia_farmacocol_UNIQUE"
	UNIQUE ("famiglia_farmacocol")
GO
