/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: TABLE
*/
ALTER TABLE "utenti"
	DROP INDEX "username_UNIQUE"
GO
DROP TABLE "utenti"
GO
CREATE TABLE "utenti"  ( 
	"idutenti"        	int(11) NOT NULL,
	"nome"            	varchar(25) NOT NULL,
	"cognome"         	varchar(25) NOT NULL,
	"password"        	varchar(45) NOT NULL,
	"username"        	varchar(12) NOT NULL,
	"data_inserimento"	timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"data_fine"       	date COMMENT 'da inserire per disattivare l''utente'  NULL,
	PRIMARY KEY("idutenti")
)
GO
ALTER TABLE "utenti"
	ADD CONSTRAINT "username_UNIQUE"
	UNIQUE ("username")
GO
