/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: VIEW
*/
DROP VIEW "vdiagnosimalattia"
GO
CREATE VIEW "vdiagnosimalattia"
AS
select `pa`.`idPAZIENTE` AS `idPaziente`,`pa`.`NOME` AS `nome`,`pa`.`COGNOME` AS `cognome`,`pa`.`DATA_NASCITA` AS `data_nascita`,`dm`.`iddiagnosi_malattia` AS `iddiagnosi_malattia`,`dm`.`cod_malattia` AS `cod_malattia`,`dm`.`data_diagnosi` AS `data_diagnosi`,`tm`.`descrizione` AS `malattia`,`tm`.`cod_tipo_malattia` AS `cod_tipo_malattia`,`tr_ant`.`idtipo_risposta` AS `anticorpi`,`tr_fatt`.`idtipo_risposta` AS `fattore_reumatoide` from ((((`artrite`.`diagnosi_malattia` `dm` left join `artrite`.`tipo_malattia` `tm` on((`tm`.`idtipo_malattia` = `dm`.`cod_malattia`))) left join `artrite`.`tipo_risposta` `tr_ant` on((`tr_ant`.`idtipo_risposta` = `dm`.`anticorpi`))) left join `artrite`.`tipo_risposta` `tr_fatt` on((`tr_fatt`.`idtipo_risposta` = `dm`.`fattore_reumatoide`))) left join `artrite`.`paziente` `pa` on((`pa`.`idPAZIENTE` = `dm`.`id_paziente`)))
GO
