/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: VIEW
*/
DROP VIEW "vpazienti"
GO
CREATE VIEW "vpazienti"
AS
select `p`.`idPAZIENTE` AS `idPAZIENTE`,`p`.`NOME` AS `NOME`,`p`.`COGNOME` AS `COGNOME`,`p`.`DATA_NASCITA` AS `DATA_NASCITA`,`p`.`CODICE_FISCALE` AS `CODICE_FISCALE`,`tm`.`descrizione` AS `MALATTIA`,`d`.`data_diagnosi` AS `DATA_DIAGNOSI`,`t`.`data_inizio` AS `DATA_TERAPIA`,((year(now()) - year(`p`.`DATA_NASCITA`)) - (date_format(now(),'%m%d') < date_format(`p`.`DATA_NASCITA`,'%m%d'))) AS `eta`,(select max(`i`.`data_infusione`) from `artrite`.`infusioni_tcz` `i` where (`i`.`id_paziente` = `p`.`idPAZIENTE`)) AS `data_infusione` from (((`artrite`.`paziente` `p` left join `artrite`.`diagnosi_malattia` `d` on((`d`.`id_paziente` = `p`.`idPAZIENTE`))) left join `artrite`.`terapia` `t` on((`t`.`id_paziente` = `p`.`idPAZIENTE`))) left join `artrite`.`tipo_malattia` `tm` on((`tm`.`idtipo_malattia` = `d`.`cod_malattia`))) where (`p`.`attivo` = 1) order by `p`.`idPAZIENTE`
GO
