/*
Script generated by Aqua Data Studio 10.0.10_01 on apr-27-2014 04:07:00 PM
Database: artrite
Schema: <All Schemas>
Objects: VIEW
*/
DROP VIEW "vterapia_farmacologica_pre"
GO
CREATE VIEW "vterapia_farmacologica_pre"
AS
select `p`.`idPAZIENTE` AS `idPaziente`,`p`.`NOME` AS `NOME`,`p`.`COGNOME` AS `COGNOME`,`p`.`DATA_NASCITA` AS `DATA_NASCITA`,`tp`.`idterapia_farmacologica_pre` AS `idterapia_farmacologica_pre`,`tp`.`cod_tipo_farmaco` AS `cod_tipo_farmaco`,`far_fam`.`famiglia_farmacocol` AS `famiglia_farmacocol`,`far`.`nome` AS `farmaco_nome` from (((`artrite`.`paziente` `p` join `artrite`.`terapia_farmacologica_pre` `tp` on((`tp`.`id_paziente` = `p`.`idPAZIENTE`))) join `artrite`.`tipo_farmaco` `far` on((`far`.`idtipo_farmaco` = `tp`.`cod_tipo_farmaco`))) join `artrite`.`tipo_famiglia_farmaco` `far_fam` on((`far_fam`.`idtipo_famiglia_farmaco` = `far`.`tipo_famiglia_farmaco`)))
GO
