// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe("controllers", function() {
    //beforeEach(module("app.controllers"));

    describe("AppCtrl", function() {
      it("scope.getClass indica se l'elemento in base alla rotta è attivo o meno", inject( 
        function($rootScope, $controller) {
          var ctrl, scope;
          scope = $rootScope.$new();
          
          ctrl = $controller("AppCtrl", {
            $scope: scope,
            $location:  {}, 
            $resource:  {},
            $rootScope: {}
          });

          // test
          var rotta = '/lista';

          // simple
          scope.activeNavId = rotta;
          expect(scope.getClass('/lista')).toEqual('active');


          scope.activeNavId = rotta + '/id_oggetto';

          expect(scope.getClass('/lista')).toEqual('');
          expect(scope.getClass('/id_oggetto')).toEqual('active');
          expect(scope.getClass('/1')).toEqual('');          
        })
      );
    });


  });

}).call(this);
