// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  /* Directives*/

  angular.module('app.directives', ['app.services']).directive('appVersion', [
    'version', function(version) {
      return function(scope, elm, attrs) {
        return elm.text(version);
      };
    }
  ]);

}).call(this);
